### ISSUE TITLE
Logger Level

### ISSUE THREAD

**Issue by regueira** [cryptomkt/cryptomkt-java#4]
Hola,

Cuando conecto el socket, el logger comienza a devolver al log absolutamente todo sin dejarme poder manejar el nivel por parte de la aplicación.

https://github.com/cryptomkt/cryptomkt-java/blob/1c5634fa27a773f424a0cf869da7340f7d0720f4/src/main/java/com/cryptomkt/api/SocketImpl.java#L60

Viendo el comportamiento creo que el problema es el setLevel de la lib.

Saludos

**Comment by Insmael** [comment]
Hola, gracias por el apoyo. El sdk actual tiene un codigo fuente diferente, por lo que el cambio ya no es necesario.
